# -*- coding: utf-8 -*-
"""csPCA_Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baE-ihyZ8X9WiHnMZb_lbLo0reSd8ECW
"""

#Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

#checkpoint directory
checkpoint_dir = '/content/drive/MyDrive/unet_checkpoints'

"""# Install dependencies"""

# !pip install SimpleITK
# !pip install nibabel

"""# Import Modules"""

import os
import glob
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
import random
import SimpleITK as sitk
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score

"""# mapping_label.py"""

labels_root = "/content/drive/MyDrive/csPCA_data/csPCA/raw_csPCa_data/picai_labels"
priority_folder = "csPCa_lesion_delineations/human_expert/Pooch25"
full_path_to_check = os.path.join(labels_root, priority_folder)

print(f"Listing contents of: {labels_root}")
# !ls "{labels_root}"

print(f"\nListing contents of: {full_path_to_check}")
# !ls "{full_path_to_check}"

"""# Classes"""

# Mock main function if the import is not available
# def main():
#     print("Warning: Using mock data since 'preprocessing.mapping_labels' was not found.")
#     # Create a list of dummy file paths for demonstration
#     # In a real scenario, these would be paths to your .nii.gz or .mha files
#     dataset = [
#         (f'/path/to/image_{i}.nii.gz', f'/path/to/label_{i}.nii.gz') for i in range(100)
#     ]
#     return dataset


class T2WDataset2D(Dataset):
    """
    2D Dataset that extracts individual slices from 3D volumes.
    Much more memory efficient than 3D approach.
    """

    def __init__(self, data_list, transform=None, slice_axis=0):
        """
        Args:
            data_list: List of (image_path, label_path, is_positive) tuples
            transform: Optional transform to apply
            slice_axis: Which axis to slice (0=axial, 1=sagittal, 2=coronal)
        """
        self.slice_data = []
        self.transform = transform
        self.slice_axis = slice_axis

        # Pre-load all slice references
        print("Loading dataset and extracting slice indices...")
        for img_path, label_path, is_positive in tqdm(data_list):
            try:
                # Read the 3D volume to get number of slices
                img_sitk = sitk.ReadImage(img_path)
                img_np = sitk.GetArrayFromImage(img_sitk).astype('float32')

                # Store reference to file, slice index, and positive status
                num_slices = img_np.shape[self.slice_axis]
                for slice_idx in range(num_slices):
                    self.slice_data.append((img_path, label_path, slice_idx, is_positive))

            except Exception as e:
                print(f"Error loading {img_path}: {e}")
                continue

        print(f"Total 2D slices: {len(self.slice_data)}")

    def __len__(self):
        return len(self.slice_data)

    def __getitem__(self, idx):
        img_path, label_path, slice_idx, is_positive = self.slice_data[idx]

        try:
            # Load 3D volume
            img_np = sitk.GetArrayFromImage(sitk.ReadImage(img_path)).astype('float32')
            label_np = sitk.GetArrayFromImage(sitk.ReadImage(label_path)).astype('int')

            # Extract 2D slice
            if self.slice_axis == 0:  # Axial
                img_slice = img_np[slice_idx, :, :]
                label_slice = label_np[slice_idx, :, :]
            elif self.slice_axis == 1:  # Sagittal
                img_slice = img_np[:, slice_idx, :]
                label_slice = label_np[:, slice_idx, :]
            else:  # Coronal
                img_slice = img_np[:, :, slice_idx]
                label_slice = label_np[:, :, slice_idx]

        except Exception as e:
            print(f"Error reading slice: {e}")
            # Return dummy data and a default is_positive value (e.g., False)
            img_slice = np.random.rand(256, 256).astype('float32') * 255
            label_slice = (np.random.rand(256, 256) > 0.5).astype('int')
            is_positive = False # Default for dummy data


        # Convert to tensors
        img = torch.from_numpy(img_slice)
        label = torch.from_numpy(label_slice)
        is_positive_tensor = torch.tensor(is_positive, dtype=torch.bool)

        # Binarize label
        label = (label > 0).long()

        # Apply transforms
        if self.transform:
            img, label = self.transform(img, label)

        # Add channel dimension to image
        return img.unsqueeze(0), label, is_positive_tensor


# --- Transform for 2D ---
class Resize2DTransform:
    def __init__(self, target_size=(256, 256)):
        self.target_size = target_size

    def __call__(self, image, label):
        # Add batch and channel dims: (H, W) -> (1, 1, H, W)
        image = image.unsqueeze(0).unsqueeze(0)
        label = label.unsqueeze(0).unsqueeze(0).float()

        # Resize with interpolation
        resized_image = F.interpolate(image, size=self.target_size, mode='bilinear', align_corners=False)
        resized_label = F.interpolate(label, size=self.target_size, mode='nearest')

        # Remove batch and channel dims
        return resized_image.squeeze(0).squeeze(0), resized_label.squeeze(0).squeeze(0).long()


# --- Step 2: Define 2D U-Net Architecture ---
class DoubleConv2D(nn.Module):
    """(Conv2D -> BN -> ReLU) * 2"""

    def __init__(self, in_ch, out_ch):
        super(DoubleConv2D, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv(x)


class UNet2D(nn.Module):
    """
    Standard 2D U-Net architecture.
    20x less memory than 3D U-Net.
    """

    def __init__(self, in_ch=1, out_ch=1):
        super(UNet2D, self).__init__()

        # Encoder
        self.inc = DoubleConv2D(in_ch, 64)
        self.down1 = nn.Sequential(nn.MaxPool2d(2), DoubleConv2D(64, 128))
        self.down2 = nn.Sequential(nn.MaxPool2d(2), DoubleConv2D(128, 256))
        self.down3 = nn.Sequential(nn.MaxPool2d(2), DoubleConv2D(256, 512))

        # Bottleneck
        self.down4 = nn.Sequential(nn.MaxPool2d(2), DoubleConv2D(512, 1024))

        # Decoder
        self.up1 = nn.ConvTranspose2d(1024, 512, kernel_size=2, stride=2)
        self.conv_up1 = DoubleConv2D(1024, 512)

        self.up2 = nn.ConvTranspose2d(512, 256, kernel_size=2, stride=2)
        self.conv_up2 = DoubleConv2D(512, 256)

        self.up3 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.conv_up3 = DoubleConv2D(256, 128)

        self.up4 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.conv_up4 = DoubleConv2D(128, 64)

        # Output
        self.outc = nn.Conv2d(64, out_ch, kernel_size=1)

    def forward(self, x):
        # Encoder
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3) # Corrected line
        x5 = self.down4(x4)

        # Decoder with skip connections
        x = self.up1(x5)
        x = torch.cat([x, x4], dim=1)
        x = self.conv_up1(x)

        x = self.up2(x)
        x = torch.cat([x, x3], dim=1)
        x = self.conv_up2(x)

        x = self.up3(x)
        x = torch.cat([x, x2], dim=1)
        x = self.conv_up3(x)

        x = self.up4(x)
        x = torch.cat([x, x1], dim=1)
        x = self.conv_up4(x)

        # Remove sigmoid from here
        x = self.outc(x)
        return x

"""# Load Data"""

# --- Step 3: Data Loading ---

import os
import glob
import SimpleITK as sitk
import numpy as np
import random
from torch.utils.data import DataLoader, Dataset


##Mapping the labels
def build_label_map(labels_root):
    label_map = {}
    priorities = [
        "csPCa_lesion_delineations/human_expert/Pooch25",
        "csPCa_lesion_delineations/human_expert/resampled",
        "csPCa_lesion_delineations/human_expert/original",
        "csPCa_lesion_delineations/AI"
    ]

    for folder in priorities:
        path = os.path.join(labels_root, folder)
        for f in glob.glob(os.path.join(path, "*.nii.gz")):
            case_id = os.path.basename(f).split(".")[0]
            if case_id not in label_map:
                label_map[case_id] = f
    return label_map





##Matching stage to match the raw images with the labels

def matching_raw_labels(mri_root, label_map):
    dataset = [] # Build dataset by recursively searching T2W images
    positive_cases = []
    negative_cases = []

    for fold in range(5):
        fold_dir = os.path.join(mri_root, f"fold{fold}", f"picai_public_images_fold{fold}")

        # Recursively find all T2W images in this fold
        t2w_files = glob.glob(os.path.join(fold_dir, "**", "*t2w.mha"), recursive=True)

        for t2w_path in t2w_files:
            case_id = os.path.basename(t2w_path).split("_t2w")[0]  # Extract case ID from filename
            if case_id in label_map:
                label_path = label_map[case_id]
                # Check if the label file contains any lesions (non-zero values)
                try:
                    label_sitk = sitk.ReadImage(label_path)
                    label_np = sitk.GetArrayFromImage(label_sitk)
                    is_positive = np.any(label_np > 0)

                    if is_positive:
                        positive_cases.append((t2w_path, label_path, True))
                    else:
                        negative_cases.append((t2w_path, label_path, False))

                except Exception as e:
                    print(f"Error reading label file {label_path}: {e}")
                    continue

            else:
                # print(f"No label found for case {case_id}") # Commented out to avoid too much output
                pass

    # Combine positive and negative cases
    dataset = positive_cases + negative_cases

    print(f"Total positive cases found: {len(positive_cases)}")
    print(f"Total negative cases found: {len(negative_cases)}")
    print("Final dataset size (t2w only):", len(dataset))


    return dataset


def main():
    ##Creating a label map
    labels_root = "/content/drive/MyDrive/csPCA_data/csPCA/raw_csPCa_data/picai_labels" # Corrected path
    label_map = build_label_map(labels_root)
    print(f"Total labels found: {len(label_map)}")  # should be ~1500


    ##Matching the raw data with the labelled map
    mri_root = "/content/drive/MyDrive/csPCA_data/csPCA/raw_csPCa_data/mri_images" # Corrected path
    matching_dict = matching_raw_labels(mri_root, label_map)
    return matching_dict
    # print(matching_dict)



if __name__ == '__main__':
    matching_dict = main()
    # You can now use matching_dict to access corresponding MRI and label paths
    # For example, to get the first pair:
    if matching_dict:
        # Find the first positive and negative case for demonstration
        first_positive = next(((mri, label, is_pos) for mri, label, is_pos in matching_dict if is_pos), None)
        first_negative = next(((mri, label, is_pos) for mri, label, is_pos in matching_dict if not is_pos), None)

        if first_positive:
            print("\nExample of a matching positive pair:")
            print(f"MRI Image Path: {first_positive[0]}")
            print(f"Label Map Path: {first_positive[1]}")
        if first_negative:
            print("\nExample of a matching negative pair:")
            print(f"MRI Image Path: {first_negative[0]}")
            print(f"Label Map Path: {first_negative[1]}")

    else:
        print("\nNo matching MRI and label pairs found.")


dataset = main() # Call the main function directly
print(f"Dataset size: {len(dataset)}")

# Filter for a smaller balanced dataset
num_positive_to_use = 20
num_negative_to_use = 20

positive_cases = [case for case in dataset if case[2] is True]
negative_cases = [case for case in dataset if case[2] is False]

# Ensure we don't request more cases than available
num_positive_to_use = min(num_positive_to_use, len(positive_cases))
num_negative_to_use = min(num_negative_to_use, len(negative_cases))

# Randomly select cases
random.shuffle(positive_cases)
random.shuffle(negative_cases)

balanced_dataset = positive_cases[:num_positive_to_use] + negative_cases[:num_negative_to_use]

print(f"\nUsing a balanced dataset with {len(positive_cases)} positive and {len(negative_cases)} negative cases.")
print(f"Selected {len(balanced_dataset)} cases for the balanced dataset.")


random.shuffle(balanced_dataset) # Shuffle the combined dataset

# Use the balanced dataset for splitting
train = balanced_dataset[:int(0.8 * len(balanced_dataset))]
val = balanced_dataset[int(0.8 * len(balanced_dataset)):int(0.9 * len(balanced_dataset))]
test = balanced_dataset[int(0.9 * len(balanced_dataset)):]

print(f"Train: {len(train)}, Val: {len(val)}, Test: {len(test)}")

# Create 2D datasets
resize_transform = Resize2DTransform(target_size=(256, 256))

train_dataset = T2WDataset2D(train, transform=resize_transform, slice_axis=0)
val_dataset = T2WDataset2D(val, transform=resize_transform, slice_axis=0)
test_dataset = T2WDataset2D(test, transform=resize_transform, slice_axis=0)

# DataLoaders - can use larger batch size with 2D!
batch_size = 8  # Much larger than 3D
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=4)

print("\nChecking batch shape...")
for img, label, is_positive in train_loader:
    print(f"Image batch: {img.shape}")  # [B, 1, 256, 256]
    print(f"Label batch: {label.shape}")  # [B, 256, 256]
    print(f"Is positive batch: {is_positive.shape}") # [B]
    break

"""# Model Setup"""

# --- Step 4: Model Setup ---
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Dice Loss Implementation
class DiceLoss(nn.Module):
    def __init__(self, smooth=1e-6):
        super(DiceLoss, self).__init__()
        self.smooth = smooth

    def forward(self, inputs, targets):
        # Apply sigmoid to get probabilities
        inputs = torch.sigmoid(inputs)

        # Flatten label and prediction tensors
        inputs = inputs.view(-1)
        targets = targets.view(-1)

        intersection = (inputs * targets).sum()
        dice = (2.*intersection + self.smooth)/(inputs.sum() + targets.sum() + self.smooth)

        return 1 - dice


model = UNet2D(in_ch=1, out_ch=1)
# Change criterion to DiceLoss
criterion = DiceLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
model.to(device)

"""# Training block with checkpoints save"""

# --- Step 5: Training Functions ---
def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0

    for images, labels, is_positive in tqdm(dataloader, desc="Training"):
        images = images.to(device)
        labels = labels.to(device).float().unsqueeze(1)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

    return running_loss / len(dataloader.dataset)


def validate_one_epoch(model, dataloader, criterion, device):
    model.eval()
    running_loss = 0.0

    with torch.no_grad():
        for images, labels, is_positive in tqdm(dataloader, desc="Validation"):
            images = images.to(device)
            labels = labels.to(device).float().unsqueeze(1)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)

    return running_loss / len(dataloader.dataset)

# --- Step 7: Evaluation Functions ---
def calculate_dice_coefficient(pred, target, smooth=1e-8):
    # Ensure inputs are binary (0 or 1)
    pred = pred.long()
    target = target.long()
    intersection = (pred * target).sum().item()
    dice = (2. * intersection + smooth) / (pred.sum().item() + target.sum().item() + smooth)
    return dice


def calculate_iou(pred, target, smooth=1e-8):
    # Ensure inputs are binary (0 or 1)
    pred = pred.long()
    target = target.long()
    intersection = (pred * target).sum().item()
    union = pred.sum().item() + target.sum().item() - intersection
    iou = (intersection + smooth) / (union + smooth)
    return iou


def test_model_comprehensive(model, test_loader, device, threshold=0.5):
    model.eval()

    all_predictions = []
    all_targets = []
    dice_scores = []
    iou_scores = []

    with torch.no_grad():
        for images, labels, is_positive in tqdm(test_loader, desc="Testing"):
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            # Apply sigmoid and threshold here to get binary predictions for metrics
            predictions = (torch.sigmoid(outputs) > threshold).float().squeeze(1)

            # Collect for global metrics
            all_predictions.extend(predictions.cpu().numpy().flatten())
            all_targets.extend(labels.cpu().numpy().flatten())

            # Calculate per-image dice and iou
            for i in range(predictions.shape[0]):
                # Pass binary predictions to metric functions
                dice = calculate_dice_coefficient(predictions[i], labels[i].float())
                iou = calculate_iou(predictions[i], labels[i].float())
                dice_scores.append(dice)
                iou_scores.append(iou)

    # Convert to 0,1 ints for scikit metrics
    all_predictions = np.array(all_predictions).round().astype(int)
    all_targets = np.array(all_targets).round().astype(int)

    accuracy = accuracy_score(all_targets, all_predictions)
    f1 = f1_score(all_targets, all_predictions, average='binary')
    precision = precision_score(all_targets, all_predictions, average='binary')
    recall = recall_score(all_targets, all_predictions, average='binary')
    confmat = confusion_matrix(all_targets, all_predictions)

    return {
        'accuracy': accuracy,
        'f1_score': f1,
        'precision': precision,
        'recall': recall,
        'dice_coefficient': np.mean(dice_scores),
        'iou_score': np.mean(iou_scores),
        'confusion_matrix': confmat
    }


def print_test_results(test_results):
    print("\n" + "=" * 50)
    print("         MODEL EVALUATION RESULTS")
    print("=" * 50)
    print(f"Accuracy        : {test_results['accuracy']:.4f}")
    print(f"F1 Score        : {test_results['f1_score']:.4f}")
    print(f"Precision       : {test_results['precision']:.4f}")
    print(f"Recall          : {test_results['recall']:.4f}")
    print(f"Dice Coefficient: {test_results['dice_coefficient']:.4f}")
    print(f"IoU Score       : {test_results['iou_score']:.4f}")
    print("=" * 50)
    print("Confusion Matrix:\n", test_results['confusion_matrix'])


# --- Step 6: Training Loop with CHECKPOINTING ---
num_epochs = 10
best_val_loss = float('inf')
patience = 3
patience_counter = 0
# Use the checkpoint directory defined in the first cell for Google Drive
# checkpoint_dir = 'checkpoints'  # ← Models save here

# Create directory if it doesn't exist
os.makedirs(checkpoint_dir, exist_ok=True)

# Use the specified filename
checkpoint_filename = "2D_unet_segmentation_balanced_dataset.pth"
best_checkpoint_path = os.path.join(checkpoint_dir, checkpoint_filename)

# Load checkpoint if it exists
start_epoch = 0
if os.path.exists(best_checkpoint_path):
    print(f"Loading checkpoint from {best_checkpoint_path}")
    # Remove map_location to load checkpoint onto the appropriate device
    checkpoint = torch.load(best_checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_loss = checkpoint['val_loss']
    print(f"Resuming training from epoch {start_epoch}")
else:
    print(f"No checkpoint found at {best_checkpoint_path}. Starting training from epoch 0.")


# Mixed precision for speed
scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None

for epoch in range(start_epoch, num_epochs):
    # Training
    model.train()
    running_loss = 0.0
    for images, labels, is_positive in tqdm(train_loader, desc="Training"):
        images = images.to(device)
        labels = labels.to(device).float().unsqueeze(1)
        optimizer.zero_grad()

        if scaler:
            with torch.cuda.amp.autocast():
                outputs = model(images)
                loss = criterion(outputs, labels)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
        running_loss += loss.item() * images.size(0)
    train_loss = running_loss / len(train_loader.dataset)

    # Validation
    val_loss = validate_one_epoch(model, val_loader, criterion, device)
    print(f'Epoch [{epoch+1}/{num_epochs}], Train: {train_loss:.4f}, Val: {val_loss:.4f}')

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_loss': val_loss,
        }, best_checkpoint_path)
        print(f'✅ Best model saved to {best_checkpoint_path}!')
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print(f'🛑 Early stopping!')
            break

print("Training complete!")

# Load best model (this will load the best model saved during the entire training run)
if os.path.exists(best_checkpoint_path):
    print(f"Loading best model checkpoint from {best_checkpoint_path} for final evaluation!")
    # Remove map_location to load checkpoint onto the appropriate device
    checkpoint = torch.load(best_checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
else:
    print("No checkpoint found for final evaluation.")

# --- Step 8: Run Final Test/Evaluation ---
# Experiment with a lower threshold
test_results = test_model_comprehensive(model, test_loader, device, threshold=0.1) # Lowered threshold
print_test_results(test_results)

# # --- Step 5: Training Functions ---
# def train_one_epoch(model, dataloader, criterion, optimizer, device):
#     model.train()
#     running_loss = 0.0

#     for images, labels in tqdm(dataloader, desc="Training"):
#         images = images.to(device)
#         labels = labels.to(device).float().unsqueeze(1)

#         outputs = model(images)
#         loss = criterion(outputs, labels)

#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#         running_loss += loss.item() * images.size(0)

#     return running_loss / len(dataloader.dataset)


# def validate_one_epoch(model, dataloader, criterion, device):
#     model.eval()
#     running_loss = 0.0

#     with torch.no_grad():
#         for images, labels in tqdm(dataloader, desc="Validation"):
#             images = images.to(device)
#             labels = labels.to(device).float().unsqueeze(1)

#             outputs = model(images)
#             loss = criterion(outputs, labels)

#             running_loss += loss.item() * images.size(0)

#     return running_loss / len(dataloader.dataset)


# # --- Step 6: Training Loop with CHECKPOINTING ---
# num_epochs = 10
# best_val_loss = float('inf')
# patience = 3
# patience_counter = 0
# # Use the checkpoint directory defined in the first cell for Google Drive
# # checkpoint_dir = 'checkpoints'  # ← Models save here

# # Create directory if it doesn't exist
# os.makedirs(checkpoint_dir, exist_ok=True)

# # Use the specified filename
# checkpoint_filename = "2D_unet_segmentation_oct9.pth"
# best_checkpoint_path = os.path.join(checkpoint_dir, checkpoint_filename)


# # Mixed precision for speed
# scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None

# for epoch in range(num_epochs):
#     # Training
#     model.train()
#     running_loss = 0.0
#     for images, labels in tqdm(train_loader, desc="Training"):
#         images = images.to(device)
#         labels = labels.to(device).float().unsqueeze(1)
#         optimizer.zero_grad()

#         if scaler:
#             with torch.cuda.amp.autocast():
#                 outputs = model(images)
#                 loss = criterion(outputs, labels)
#             scaler.scale(loss).backward()
#             scaler.step(optimizer)
#             scaler.update()
#         else:
#             outputs = model(images)
#             loss = criterion(outputs, labels)
#             loss.backward()
#             optimizer.step()
#         running_loss += loss.item() * images.size(0)
#     train_loss = running_loss / len(train_loader.dataset)

#     # Validation
#     val_loss = validate_one_epoch(model, val_loader, criterion, device)
#     print(f'Epoch [{epoch+1}/{num_epochs}], Train: {train_loss:.4f}, Val: {val_loss:.4f}')

#     # Save best model
#     if val_loss < best_val_loss:
#         best_val_loss = val_loss
#         patience_counter = 0
#         torch.save({
#             'epoch': epoch,
#             'model_state_dict': model.state_dict(),
#             'optimizer_state_dict': optimizer.state_dict(),
#             'val_loss': val_loss,
#         }, best_checkpoint_path)
#         print(f'✅ Best model saved to {best_checkpoint_path}!')
#     else:
#         patience_counter += 1
#         if patience_counter >= patience:
#             print(f'🛑 Early stopping!')
#             break

# print("Training complete!")

# # Load best model
# checkpoint = torch.load(best_checkpoint_path)
# model.load_state_dict(checkpoint['model_state_dict'])
# print(f"Loaded best model checkpoint from {best_checkpoint_path}!")

# # --- Step 7: Evaluation Functions ---
# def calculate_dice_coefficient(pred, target, smooth=1e-8):
#     # Apply sigmoid to predictions before calculating metrics
#     pred = torch.sigmoid(pred)
#     intersection = (pred * target).sum().item()
#     dice = (2. * intersection + smooth) / (pred.sum().item() + target.sum().item() + smooth)
#     return dice


# def calculate_iou(pred, target, smooth=1e-8):
#     # Apply sigmoid to predictions before calculating metrics
#     pred = torch.sigmoid(pred)
#     intersection = (pred * target).sum().item()
#     union = pred.sum().item() + target.sum().item() - intersection
#     iou = (intersection + smooth) / (union + smooth)
#     return iou


# def test_model_comprehensive(model, test_loader, device, threshold=0.5):
#     model.eval()

#     all_predictions = []
#     all_targets = []
#     dice_scores = []
#     iou_scores = []

#     with torch.no_grad():
#         for images, labels in tqdm(test_loader, desc="Testing"):
#             images = images.to(device)
#             labels = labels.to(device)

#             # Apply sigmoid to outputs here for thresholding
#             outputs = torch.sigmoid(model(images))
#             predictions = (outputs > threshold).float().squeeze(1)

#             # Collect for global metrics
#             all_predictions.extend(predictions.cpu().numpy().flatten())
#             all_targets.extend(labels.cpu().numpy().flatten())

#             # Calculate per-image dice and iou
#             for i in range(predictions.shape[0]):
#                 # Pass raw predictions to metric functions which now handle sigmoid
#                 dice = calculate_dice_coefficient(outputs[i].squeeze(0), labels[i].float())
#                 iou = calculate_iou(outputs[i].squeeze(0), labels[i].float())
#                 dice_scores.append(dice)
#                 iou_scores.append(iou)


#     # Convert to 0,1 ints for scikit metrics
#     all_predictions = np.array(all_predictions).round().astype(int)
#     all_targets = np.array(all_targets).round().astype(int)

#     accuracy = accuracy_score(all_targets, all_predictions)
#     f1 = f1_score(all_targets, all_predictions, average='binary')
#     precision = precision_score(all_targets, all_predictions, average='binary')
#     recall = recall_score(all_targets, all_predictions, average='binary')
#     confmat = confusion_matrix(all_targets, all_predictions)

#     return {
#         'accuracy': accuracy,
#         'f1_score': f1,
#         'precision': precision,
#         'recall': recall,
#         'dice_coefficient': np.mean(dice_scores),
#         'iou_score': np.mean(iou_scores),
#         'confusion_matrix': confmat
#     }


# def print_test_results(test_results):
#     print("\n" + "=" * 50)
#     print("         MODEL EVALUATION RESULTS")
#     print("=" * 50)
#     print(f"Accuracy        : {test_results['accuracy']:.4f}")
#     print(f"F1 Score        : {test_results['f1_score']:.4f}")
#     print(f"Precision       : {test_results['precision']:.4f}")
#     print(f"Recall          : {test_results['recall']:.4f}")
#     print(f"Dice Coefficient: {test_results['dice_coefficient']:.4f}")
#     print(f"IoU Score       : {test_results['iou_score']:.4f}")
#     print("=" * 50)
#     print("Confusion Matrix:\n", test_results['confusion_matrix'])

# # --- Step 5: Training Functions ---
# def train_one_epoch(model, dataloader, criterion, optimizer, device):
#     model.train()
#     running_loss = 0.0

#     for images, labels, is_positive in tqdm(dataloader, desc="Training"):
#         images = images.to(device)
#         labels = labels.to(device).float().unsqueeze(1)

#         outputs = model(images)
#         loss = criterion(outputs, labels)

#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#         running_loss += loss.item() * images.size(0)

#     return running_loss / len(dataloader.dataset)


# def validate_one_epoch(model, dataloader, criterion, device):
#     model.eval()
#     running_loss = 0.0

#     with torch.no_grad():
#         for images, labels, is_positive in tqdm(dataloader, desc="Validation"):
#             images = images.to(device)
#             labels = labels.to(device).float().unsqueeze(1)

#             outputs = model(images)
#             loss = criterion(outputs, labels)

#             running_loss += loss.item() * images.size(0)

#     return running_loss / len(dataloader.dataset)


# # --- Step 6: Training Loop with CHECKPOINTING ---
# num_epochs = 10
# best_val_loss = float('inf')
# patience = 3
# patience_counter = 0
# # Use the checkpoint directory defined in the first cell for Google Drive
# # checkpoint_dir = 'checkpoints'  # ← Models save here

# # Create directory if it doesn't exist
# os.makedirs(checkpoint_dir, exist_ok=True)

# # Use the specified filename
# checkpoint_filename = "2D_unet_segmentation_balanced_dataset.pth"
# best_checkpoint_path = os.path.join(checkpoint_dir, checkpoint_filename)


# # Mixed precision for speed
# scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None

# for epoch in range(num_epochs):
#     # Training
#     model.train()
#     running_loss = 0.0
#     for images, labels, is_positive in tqdm(train_loader, desc="Training"):
#         images = images.to(device)
#         labels = labels.to(device).float().unsqueeze(1)
#         optimizer.zero_grad()

#         if scaler:
#             with torch.cuda.amp.autocast():
#                 outputs = model(images)
#                 loss = criterion(outputs, labels)
#             scaler.scale(loss).backward()
#             scaler.step(optimizer)
#             scaler.update()
#         else:
#             outputs = model(images)
#             loss = criterion(outputs, labels)
#             loss.backward()
#             optimizer.step()
#         running_loss += loss.item() * images.size(0)
#     train_loss = running_loss / len(train_loader.dataset)

#     # Validation
#     val_loss = validate_one_epoch(model, val_loader, criterion, device)
#     print(f'Epoch [{epoch+1}/{num_epochs}], Train: {train_loss:.4f}, Val: {val_loss:.4f}')

#     # Save best model
#     if val_loss < best_val_loss:
#         best_val_loss = val_loss
#         patience_counter = 0
#         torch.save({
#             'epoch': epoch,
#             'model_state_dict': model.state_dict(),
#             'optimizer_state_dict': optimizer.state_dict(),
#             'val_loss': val_loss,
#         }, best_checkpoint_path)
#         print(f'✅ Best model saved to {best_checkpoint_path}!')
#     else:
#         patience_counter += 1
#         if patience_counter >= patience:
#             print(f'🛑 Early stopping!')
#             break

# print("Training complete!")

# # Load best model
# checkpoint = torch.load(best_checkpoint_path)
# model.load_state_dict(checkpoint['model_state_dict'])
# print(f"Loaded best model checkpoint from {best_checkpoint_path}!")

# # --- Step 7: Evaluation Functions ---
# def calculate_dice_coefficient(pred, target, smooth=1e-8):
#     # Ensure inputs are binary (0 or 1)
#     pred = pred.long()
#     target = target.long()
#     intersection = (pred * target).sum().item()
#     dice = (2. * intersection + smooth) / (pred.sum().item() + target.sum().item() + smooth)
#     return dice


# def calculate_iou(pred, target, smooth=1e-8):
#     # Ensure inputs are binary (0 or 1)
#     pred = pred.long()
#     target = target.long()
#     intersection = (pred * target).sum().item()
#     union = pred.sum().item() + target.sum().item() - intersection
#     iou = (intersection + smooth) / (union + smooth)
#     return iou


# def test_model_comprehensive(model, test_loader, device, threshold=0.5):
#     model.eval()

#     all_predictions = []
#     all_targets = []
#     dice_scores = []
#     iou_scores = []

#     with torch.no_grad():
#         for images, labels, is_positive in tqdm(test_loader, desc="Testing"):
#             images = images.to(device)
#             labels = labels.to(device)

#             outputs = model(images)
#             # Apply sigmoid and threshold here to get binary predictions for metrics
#             predictions = (torch.sigmoid(outputs) > threshold).float().squeeze(1)

#             # Collect for global metrics
#             all_predictions.extend(predictions.cpu().numpy().flatten())
#             all_targets.extend(labels.cpu().numpy().flatten())

#             # Calculate per-image dice and iou
#             for i in range(predictions.shape[0]):
#                 # Pass binary predictions to metric functions
#                 dice = calculate_dice_coefficient(predictions[i], labels[i].float())
#                 iou = calculate_iou(predictions[i], labels[i].float())
#                 dice_scores.append(dice)
#                 iou_scores.append(iou)

#     # Convert to 0,1 ints for scikit metrics
#     all_predictions = np.array(all_predictions).round().astype(int)
#     all_targets = np.array(all_targets).round().astype(int)

#     accuracy = accuracy_score(all_targets, all_predictions)
#     f1 = f1_score(all_targets, all_predictions, average='binary')
#     precision = precision_score(all_targets, all_predictions, average='binary')
#     recall = recall_score(all_targets, all_predictions, average='binary')
#     confmat = confusion_matrix(all_targets, all_predictions)

#     return {
#         'accuracy': accuracy,
#         'f1_score': f1,
#         'precision': precision,
#         'recall': recall,
#         'dice_coefficient': np.mean(dice_scores),
#         'iou_score': np.mean(iou_scores),
#         'confusion_matrix': confmat
#     }


# def print_test_results(test_results):
#     print("\n" + "=" * 50)
#     print("         MODEL EVALUATION RESULTS")
#     print("=" * 50)
#     print(f"Accuracy        : {test_results['accuracy']:.4f}")
#     print(f"F1 Score        : {test_results['f1_score']:.4f}")
#     print(f"Precision       : {test_results['precision']:.4f}")
#     print(f"Recall          : {test_results['recall']:.4f}")
#     print(f"Dice Coefficient: {test_results['dice_coefficient']:.4f}")
#     print(f"IoU Score       : {test_results['iou_score']:.4f}")
#     print("=" * 50)
#     print("Confusion Matrix:\n", test_results['confusion_matrix'])

"""# Save Test Results"""

import json
import os

# Define the path to save the test results
# Use the same checkpoint_dir as defined earlier
results_filename = "2D_unet_segmentation_oct14_smallsubset.json"
results_path = os.path.join(checkpoint_dir, results_filename)

# Ensure the directory exists
os.makedirs(checkpoint_dir, exist_ok=True)

# Save the test results to a JSON file
with open(results_path, 'w') as f:
    json.dump(test_results, f, indent=4)

print(f"Test results saved to {results_path}")

"""# Visualization"""

# --- Step 7: Evaluation Functions ---
# Moved to the training cell to avoid NameError

def visualize_2d_prediction(model, dataset, device, sample_idx=0):
    model.eval()

    img_tensor, label_tensor, _ = dataset[sample_idx] # Added is_positive to unpacking
    input_tensor = img_tensor.unsqueeze(0).to(device)

    with torch.no_grad():
        output_tensor = model(input_tensor)

    img_cpu = img_tensor.squeeze(0).cpu().numpy()
    label_cpu = label_tensor.cpu().numpy()
    # Apply sigmoid to outputs here for thresholding
    pred_cpu = (torch.sigmoid(output_tensor) > 0.5).squeeze().cpu().numpy()


    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(img_cpu, cmap='bone')
    axes[0].set_title(f'Original MRI Slice (Sample {sample_idx})')
    axes[0].axis('off')

    axes[1].imshow(label_cpu, cmap='gray')
    axes[1].set_title('Ground Truth')
    axes[1].axis('off')

    axes[2].imshow(pred_cpu, cmap='gray')
    axes[2].set_title('Prediction (Threshold 0.5)')
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

# --- Step 9: Run Final Test/Evaluation ---
# Moved test_model_comprehensive and print_test_results to the training cell

# Visualize a few samples (choose indices available in your test set)
num_samples_to_visualize = 3
for i in range(num_samples_to_visualize):
  # Ensure sample_idx is within the bounds of the dataset
  sample_idx_to_visualize = min(i * 5, len(test_dataset) - 1) # Visualize samples 0, 5, 10 (or fewer if dataset is small)
  visualize_2d_prediction(model, test_dataset, device, sample_idx=sample_idx_to_visualize)